syntax = "proto3";
package sub.internal.grpc.pb;

option go_package = "github.com/brezzgg/sub/internal/grpc/pb";

service SubService {
  rpc Set(SetRequest) returns (Empty);
  rpc Get(GetRequest) returns (GetResponse);
  rpc GetAll(Empty) returns (GetAllResponse);
}

message SetRequest {
    string id = 1;
    bytes payload = 2;
    int64 ttl = 3;
}

message GetRequest {
    string id = 1;
}

message GetResponse {
    bytes payload = 1;
    int64 ttl = 2;
    int64 created_at = 3;
}

message GetAllResponse {
    map<string, GetResponse> Subscriptions = 1;
}

message Empty {}
