// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.7
// 	protoc        v4.25.1
// source: internal/transport/grpc/pb/service.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type SetRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Payload       []byte                 `protobuf:"bytes,2,opt,name=payload,proto3" json:"payload,omitempty"`
	Ttl           int64                  `protobuf:"varint,3,opt,name=ttl,proto3" json:"ttl,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SetRequest) Reset() {
	*x = SetRequest{}
	mi := &file_internal_transport_grpc_pb_service_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetRequest) ProtoMessage() {}

func (x *SetRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_transport_grpc_pb_service_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetRequest.ProtoReflect.Descriptor instead.
func (*SetRequest) Descriptor() ([]byte, []int) {
	return file_internal_transport_grpc_pb_service_proto_rawDescGZIP(), []int{0}
}

func (x *SetRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *SetRequest) GetPayload() []byte {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *SetRequest) GetTtl() int64 {
	if x != nil {
		return x.Ttl
	}
	return 0
}

type GetRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetRequest) Reset() {
	*x = GetRequest{}
	mi := &file_internal_transport_grpc_pb_service_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetRequest) ProtoMessage() {}

func (x *GetRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_transport_grpc_pb_service_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetRequest.ProtoReflect.Descriptor instead.
func (*GetRequest) Descriptor() ([]byte, []int) {
	return file_internal_transport_grpc_pb_service_proto_rawDescGZIP(), []int{1}
}

func (x *GetRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type GetResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Payload       []byte                 `protobuf:"bytes,1,opt,name=payload,proto3" json:"payload,omitempty"`
	Ttl           int64                  `protobuf:"varint,2,opt,name=ttl,proto3" json:"ttl,omitempty"`
	CreatedAt     int64                  `protobuf:"varint,3,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetResponse) Reset() {
	*x = GetResponse{}
	mi := &file_internal_transport_grpc_pb_service_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetResponse) ProtoMessage() {}

func (x *GetResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_transport_grpc_pb_service_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetResponse.ProtoReflect.Descriptor instead.
func (*GetResponse) Descriptor() ([]byte, []int) {
	return file_internal_transport_grpc_pb_service_proto_rawDescGZIP(), []int{2}
}

func (x *GetResponse) GetPayload() []byte {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *GetResponse) GetTtl() int64 {
	if x != nil {
		return x.Ttl
	}
	return 0
}

func (x *GetResponse) GetCreatedAt() int64 {
	if x != nil {
		return x.CreatedAt
	}
	return 0
}

type GetAllResponse struct {
	state         protoimpl.MessageState  `protogen:"open.v1"`
	Subscriptions map[string]*GetResponse `protobuf:"bytes,1,rep,name=Subscriptions,proto3" json:"Subscriptions,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetAllResponse) Reset() {
	*x = GetAllResponse{}
	mi := &file_internal_transport_grpc_pb_service_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAllResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAllResponse) ProtoMessage() {}

func (x *GetAllResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_transport_grpc_pb_service_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAllResponse.ProtoReflect.Descriptor instead.
func (*GetAllResponse) Descriptor() ([]byte, []int) {
	return file_internal_transport_grpc_pb_service_proto_rawDescGZIP(), []int{3}
}

func (x *GetAllResponse) GetSubscriptions() map[string]*GetResponse {
	if x != nil {
		return x.Subscriptions
	}
	return nil
}

type Empty struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Empty) Reset() {
	*x = Empty{}
	mi := &file_internal_transport_grpc_pb_service_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Empty) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Empty) ProtoMessage() {}

func (x *Empty) ProtoReflect() protoreflect.Message {
	mi := &file_internal_transport_grpc_pb_service_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Empty.ProtoReflect.Descriptor instead.
func (*Empty) Descriptor() ([]byte, []int) {
	return file_internal_transport_grpc_pb_service_proto_rawDescGZIP(), []int{4}
}

var File_internal_transport_grpc_pb_service_proto protoreflect.FileDescriptor

const file_internal_transport_grpc_pb_service_proto_rawDesc = "" +
	"\n" +
	"(internal/transport/grpc/pb/service.proto\x12\x14sub.internal.grpc.pb\"H\n" +
	"\n" +
	"SetRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x18\n" +
	"\apayload\x18\x02 \x01(\fR\apayload\x12\x10\n" +
	"\x03ttl\x18\x03 \x01(\x03R\x03ttl\"\x1c\n" +
	"\n" +
	"GetRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"X\n" +
	"\vGetResponse\x12\x18\n" +
	"\apayload\x18\x01 \x01(\fR\apayload\x12\x10\n" +
	"\x03ttl\x18\x02 \x01(\x03R\x03ttl\x12\x1d\n" +
	"\n" +
	"created_at\x18\x03 \x01(\x03R\tcreatedAt\"\xd4\x01\n" +
	"\x0eGetAllResponse\x12]\n" +
	"\rSubscriptions\x18\x01 \x03(\v27.sub.internal.grpc.pb.GetAllResponse.SubscriptionsEntryR\rSubscriptions\x1ac\n" +
	"\x12SubscriptionsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x127\n" +
	"\x05value\x18\x02 \x01(\v2!.sub.internal.grpc.pb.GetResponseR\x05value:\x028\x01\"\a\n" +
	"\x05Empty2\xeb\x01\n" +
	"\n" +
	"SubService\x12D\n" +
	"\x03Set\x12 .sub.internal.grpc.pb.SetRequest\x1a\x1b.sub.internal.grpc.pb.Empty\x12J\n" +
	"\x03Get\x12 .sub.internal.grpc.pb.GetRequest\x1a!.sub.internal.grpc.pb.GetResponse\x12K\n" +
	"\x06GetAll\x12\x1b.sub.internal.grpc.pb.Empty\x1a$.sub.internal.grpc.pb.GetAllResponseB)Z'github.com/brezzgg/sub/internal/grpc/pbb\x06proto3"

var (
	file_internal_transport_grpc_pb_service_proto_rawDescOnce sync.Once
	file_internal_transport_grpc_pb_service_proto_rawDescData []byte
)

func file_internal_transport_grpc_pb_service_proto_rawDescGZIP() []byte {
	file_internal_transport_grpc_pb_service_proto_rawDescOnce.Do(func() {
		file_internal_transport_grpc_pb_service_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_internal_transport_grpc_pb_service_proto_rawDesc), len(file_internal_transport_grpc_pb_service_proto_rawDesc)))
	})
	return file_internal_transport_grpc_pb_service_proto_rawDescData
}

var file_internal_transport_grpc_pb_service_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_internal_transport_grpc_pb_service_proto_goTypes = []any{
	(*SetRequest)(nil),     // 0: sub.internal.grpc.pb.SetRequest
	(*GetRequest)(nil),     // 1: sub.internal.grpc.pb.GetRequest
	(*GetResponse)(nil),    // 2: sub.internal.grpc.pb.GetResponse
	(*GetAllResponse)(nil), // 3: sub.internal.grpc.pb.GetAllResponse
	(*Empty)(nil),          // 4: sub.internal.grpc.pb.Empty
	nil,                    // 5: sub.internal.grpc.pb.GetAllResponse.SubscriptionsEntry
}
var file_internal_transport_grpc_pb_service_proto_depIdxs = []int32{
	5, // 0: sub.internal.grpc.pb.GetAllResponse.Subscriptions:type_name -> sub.internal.grpc.pb.GetAllResponse.SubscriptionsEntry
	2, // 1: sub.internal.grpc.pb.GetAllResponse.SubscriptionsEntry.value:type_name -> sub.internal.grpc.pb.GetResponse
	0, // 2: sub.internal.grpc.pb.SubService.Set:input_type -> sub.internal.grpc.pb.SetRequest
	1, // 3: sub.internal.grpc.pb.SubService.Get:input_type -> sub.internal.grpc.pb.GetRequest
	4, // 4: sub.internal.grpc.pb.SubService.GetAll:input_type -> sub.internal.grpc.pb.Empty
	4, // 5: sub.internal.grpc.pb.SubService.Set:output_type -> sub.internal.grpc.pb.Empty
	2, // 6: sub.internal.grpc.pb.SubService.Get:output_type -> sub.internal.grpc.pb.GetResponse
	3, // 7: sub.internal.grpc.pb.SubService.GetAll:output_type -> sub.internal.grpc.pb.GetAllResponse
	5, // [5:8] is the sub-list for method output_type
	2, // [2:5] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_internal_transport_grpc_pb_service_proto_init() }
func file_internal_transport_grpc_pb_service_proto_init() {
	if File_internal_transport_grpc_pb_service_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_internal_transport_grpc_pb_service_proto_rawDesc), len(file_internal_transport_grpc_pb_service_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_internal_transport_grpc_pb_service_proto_goTypes,
		DependencyIndexes: file_internal_transport_grpc_pb_service_proto_depIdxs,
		MessageInfos:      file_internal_transport_grpc_pb_service_proto_msgTypes,
	}.Build()
	File_internal_transport_grpc_pb_service_proto = out.File
	file_internal_transport_grpc_pb_service_proto_goTypes = nil
	file_internal_transport_grpc_pb_service_proto_depIdxs = nil
}
