syntax = "proto3";
package sub.internal.usecase;

option go_package = "github.com/brezzgg/sub/internal/usecase";

message SubscriptionRawPb {
    string id = 1;
    string payload_body_string = 2;
    map<string, string> payload_headers = 3;
    int64 expired = 4;
    bool disabled = 5;
    MetadataRaw metadata = 6;
}

message SetRequest {
    SubscriptionRawPb raw = 1;
    repeated string bodies = 2;

    string title = 3;
    string update_interval = 4;
    string user_web_page = 5;
    string moved_permanently = 6;
    string support_uri = 7;
    string dns = 8;
    UserInfo user_info = 9;

    map<string, string> custom_headers = 10;
}

message MetadataRaw {
    bytes data = 1;
}

message UserInfo {
    int64 upload = 1;
    int64 download = 2;
    int64 total = 3;
    int64 expired = 4;
}
