// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.7
// 	protoc        v4.25.1
// source: internal/usecase/model.proto

package usecase

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type SubscriptionRawPb struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	Id                string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	PayloadBodyString string                 `protobuf:"bytes,2,opt,name=payload_body_string,json=payloadBodyString,proto3" json:"payload_body_string,omitempty"`
	PayloadHeaders    map[string]string      `protobuf:"bytes,3,rep,name=payload_headers,json=payloadHeaders,proto3" json:"payload_headers,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	Expired           int64                  `protobuf:"varint,4,opt,name=expired,proto3" json:"expired,omitempty"`
	Disabled          bool                   `protobuf:"varint,5,opt,name=disabled,proto3" json:"disabled,omitempty"`
	Metadata          *MetadataRaw           `protobuf:"bytes,6,opt,name=metadata,proto3" json:"metadata,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *SubscriptionRawPb) Reset() {
	*x = SubscriptionRawPb{}
	mi := &file_internal_usecase_model_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SubscriptionRawPb) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SubscriptionRawPb) ProtoMessage() {}

func (x *SubscriptionRawPb) ProtoReflect() protoreflect.Message {
	mi := &file_internal_usecase_model_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SubscriptionRawPb.ProtoReflect.Descriptor instead.
func (*SubscriptionRawPb) Descriptor() ([]byte, []int) {
	return file_internal_usecase_model_proto_rawDescGZIP(), []int{0}
}

func (x *SubscriptionRawPb) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *SubscriptionRawPb) GetPayloadBodyString() string {
	if x != nil {
		return x.PayloadBodyString
	}
	return ""
}

func (x *SubscriptionRawPb) GetPayloadHeaders() map[string]string {
	if x != nil {
		return x.PayloadHeaders
	}
	return nil
}

func (x *SubscriptionRawPb) GetExpired() int64 {
	if x != nil {
		return x.Expired
	}
	return 0
}

func (x *SubscriptionRawPb) GetDisabled() bool {
	if x != nil {
		return x.Disabled
	}
	return false
}

func (x *SubscriptionRawPb) GetMetadata() *MetadataRaw {
	if x != nil {
		return x.Metadata
	}
	return nil
}

type SetRequest struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	Raw              *SubscriptionRawPb     `protobuf:"bytes,1,opt,name=raw,proto3" json:"raw,omitempty"`
	Bodies           []string               `protobuf:"bytes,2,rep,name=bodies,proto3" json:"bodies,omitempty"`
	Title            string                 `protobuf:"bytes,3,opt,name=title,proto3" json:"title,omitempty"`
	UpdateInterval   string                 `protobuf:"bytes,4,opt,name=update_interval,json=updateInterval,proto3" json:"update_interval,omitempty"`
	UserWebPage      string                 `protobuf:"bytes,5,opt,name=user_web_page,json=userWebPage,proto3" json:"user_web_page,omitempty"`
	MovedPermanently string                 `protobuf:"bytes,6,opt,name=moved_permanently,json=movedPermanently,proto3" json:"moved_permanently,omitempty"`
	SupportUri       string                 `protobuf:"bytes,7,opt,name=support_uri,json=supportUri,proto3" json:"support_uri,omitempty"`
	Dns              string                 `protobuf:"bytes,8,opt,name=dns,proto3" json:"dns,omitempty"`
	CustomHeaders    map[string]string      `protobuf:"bytes,10,rep,name=custom_headers,json=customHeaders,proto3" json:"custom_headers,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *SetRequest) Reset() {
	*x = SetRequest{}
	mi := &file_internal_usecase_model_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetRequest) ProtoMessage() {}

func (x *SetRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_usecase_model_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetRequest.ProtoReflect.Descriptor instead.
func (*SetRequest) Descriptor() ([]byte, []int) {
	return file_internal_usecase_model_proto_rawDescGZIP(), []int{1}
}

func (x *SetRequest) GetRaw() *SubscriptionRawPb {
	if x != nil {
		return x.Raw
	}
	return nil
}

func (x *SetRequest) GetBodies() []string {
	if x != nil {
		return x.Bodies
	}
	return nil
}

func (x *SetRequest) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *SetRequest) GetUpdateInterval() string {
	if x != nil {
		return x.UpdateInterval
	}
	return ""
}

func (x *SetRequest) GetUserWebPage() string {
	if x != nil {
		return x.UserWebPage
	}
	return ""
}

func (x *SetRequest) GetMovedPermanently() string {
	if x != nil {
		return x.MovedPermanently
	}
	return ""
}

func (x *SetRequest) GetSupportUri() string {
	if x != nil {
		return x.SupportUri
	}
	return ""
}

func (x *SetRequest) GetDns() string {
	if x != nil {
		return x.Dns
	}
	return ""
}

func (x *SetRequest) GetCustomHeaders() map[string]string {
	if x != nil {
		return x.CustomHeaders
	}
	return nil
}

type MetadataRaw struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Data          []byte                 `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MetadataRaw) Reset() {
	*x = MetadataRaw{}
	mi := &file_internal_usecase_model_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MetadataRaw) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MetadataRaw) ProtoMessage() {}

func (x *MetadataRaw) ProtoReflect() protoreflect.Message {
	mi := &file_internal_usecase_model_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MetadataRaw.ProtoReflect.Descriptor instead.
func (*MetadataRaw) Descriptor() ([]byte, []int) {
	return file_internal_usecase_model_proto_rawDescGZIP(), []int{2}
}

func (x *MetadataRaw) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

var File_internal_usecase_model_proto protoreflect.FileDescriptor

const file_internal_usecase_model_proto_rawDesc = "" +
	"\n" +
	"\x1cinternal/usecase/model.proto\x12\x14sub.internal.usecase\"\xf1\x02\n" +
	"\x11SubscriptionRawPb\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12.\n" +
	"\x13payload_body_string\x18\x02 \x01(\tR\x11payloadBodyString\x12d\n" +
	"\x0fpayload_headers\x18\x03 \x03(\v2;.sub.internal.usecase.SubscriptionRawPb.PayloadHeadersEntryR\x0epayloadHeaders\x12\x18\n" +
	"\aexpired\x18\x04 \x01(\x03R\aexpired\x12\x1a\n" +
	"\bdisabled\x18\x05 \x01(\bR\bdisabled\x12=\n" +
	"\bmetadata\x18\x06 \x01(\v2!.sub.internal.usecase.MetadataRawR\bmetadata\x1aA\n" +
	"\x13PayloadHeadersEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\xc0\x03\n" +
	"\n" +
	"SetRequest\x129\n" +
	"\x03raw\x18\x01 \x01(\v2'.sub.internal.usecase.SubscriptionRawPbR\x03raw\x12\x16\n" +
	"\x06bodies\x18\x02 \x03(\tR\x06bodies\x12\x14\n" +
	"\x05title\x18\x03 \x01(\tR\x05title\x12'\n" +
	"\x0fupdate_interval\x18\x04 \x01(\tR\x0eupdateInterval\x12\"\n" +
	"\ruser_web_page\x18\x05 \x01(\tR\vuserWebPage\x12+\n" +
	"\x11moved_permanently\x18\x06 \x01(\tR\x10movedPermanently\x12\x1f\n" +
	"\vsupport_uri\x18\a \x01(\tR\n" +
	"supportUri\x12\x10\n" +
	"\x03dns\x18\b \x01(\tR\x03dns\x12Z\n" +
	"\x0ecustom_headers\x18\n" +
	" \x03(\v23.sub.internal.usecase.SetRequest.CustomHeadersEntryR\rcustomHeaders\x1a@\n" +
	"\x12CustomHeadersEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"!\n" +
	"\vMetadataRaw\x12\x12\n" +
	"\x04data\x18\x01 \x01(\fR\x04dataB)Z'github.com/brezzgg/sub/internal/usecaseb\x06proto3"

var (
	file_internal_usecase_model_proto_rawDescOnce sync.Once
	file_internal_usecase_model_proto_rawDescData []byte
)

func file_internal_usecase_model_proto_rawDescGZIP() []byte {
	file_internal_usecase_model_proto_rawDescOnce.Do(func() {
		file_internal_usecase_model_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_internal_usecase_model_proto_rawDesc), len(file_internal_usecase_model_proto_rawDesc)))
	})
	return file_internal_usecase_model_proto_rawDescData
}

var file_internal_usecase_model_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_internal_usecase_model_proto_goTypes = []any{
	(*SubscriptionRawPb)(nil), // 0: sub.internal.usecase.SubscriptionRawPb
	(*SetRequest)(nil),        // 1: sub.internal.usecase.SetRequest
	(*MetadataRaw)(nil),       // 2: sub.internal.usecase.MetadataRaw
	nil,                       // 3: sub.internal.usecase.SubscriptionRawPb.PayloadHeadersEntry
	nil,                       // 4: sub.internal.usecase.SetRequest.CustomHeadersEntry
}
var file_internal_usecase_model_proto_depIdxs = []int32{
	3, // 0: sub.internal.usecase.SubscriptionRawPb.payload_headers:type_name -> sub.internal.usecase.SubscriptionRawPb.PayloadHeadersEntry
	2, // 1: sub.internal.usecase.SubscriptionRawPb.metadata:type_name -> sub.internal.usecase.MetadataRaw
	0, // 2: sub.internal.usecase.SetRequest.raw:type_name -> sub.internal.usecase.SubscriptionRawPb
	4, // 3: sub.internal.usecase.SetRequest.custom_headers:type_name -> sub.internal.usecase.SetRequest.CustomHeadersEntry
	4, // [4:4] is the sub-list for method output_type
	4, // [4:4] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_internal_usecase_model_proto_init() }
func file_internal_usecase_model_proto_init() {
	if File_internal_usecase_model_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_internal_usecase_model_proto_rawDesc), len(file_internal_usecase_model_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_internal_usecase_model_proto_goTypes,
		DependencyIndexes: file_internal_usecase_model_proto_depIdxs,
		MessageInfos:      file_internal_usecase_model_proto_msgTypes,
	}.Build()
	File_internal_usecase_model_proto = out.File
	file_internal_usecase_model_proto_goTypes = nil
	file_internal_usecase_model_proto_depIdxs = nil
}
