// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.7
// 	protoc        v4.25.1
// source: internal/transport/grpc/service.proto

package grpc

import (
	usecase "github.com/brezzgg/sub/internal/usecase"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type SetRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Data:
	//
	//	*SetRequest_Raw
	//	*SetRequest_Req
	Data          isSetRequest_Data `protobuf_oneof:"data"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SetRequest) Reset() {
	*x = SetRequest{}
	mi := &file_internal_transport_grpc_service_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetRequest) ProtoMessage() {}

func (x *SetRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_transport_grpc_service_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetRequest.ProtoReflect.Descriptor instead.
func (*SetRequest) Descriptor() ([]byte, []int) {
	return file_internal_transport_grpc_service_proto_rawDescGZIP(), []int{0}
}

func (x *SetRequest) GetData() isSetRequest_Data {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *SetRequest) GetRaw() *usecase.SubscriptionRawPb {
	if x != nil {
		if x, ok := x.Data.(*SetRequest_Raw); ok {
			return x.Raw
		}
	}
	return nil
}

func (x *SetRequest) GetReq() *usecase.SetRequest {
	if x != nil {
		if x, ok := x.Data.(*SetRequest_Req); ok {
			return x.Req
		}
	}
	return nil
}

type isSetRequest_Data interface {
	isSetRequest_Data()
}

type SetRequest_Raw struct {
	Raw *usecase.SubscriptionRawPb `protobuf:"bytes,1,opt,name=raw,proto3,oneof"`
}

type SetRequest_Req struct {
	Req *usecase.SetRequest `protobuf:"bytes,2,opt,name=req,proto3,oneof"`
}

func (*SetRequest_Raw) isSetRequest_Data() {}

func (*SetRequest_Req) isSetRequest_Data() {}

type GetAllResponse struct {
	state         protoimpl.MessageState       `protogen:"open.v1"`
	Subs          []*usecase.SubscriptionRawPb `protobuf:"bytes,1,rep,name=subs,proto3" json:"subs,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetAllResponse) Reset() {
	*x = GetAllResponse{}
	mi := &file_internal_transport_grpc_service_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAllResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAllResponse) ProtoMessage() {}

func (x *GetAllResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_transport_grpc_service_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAllResponse.ProtoReflect.Descriptor instead.
func (*GetAllResponse) Descriptor() ([]byte, []int) {
	return file_internal_transport_grpc_service_proto_rawDescGZIP(), []int{1}
}

func (x *GetAllResponse) GetSubs() []*usecase.SubscriptionRawPb {
	if x != nil {
		return x.Subs
	}
	return nil
}

type IdRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *IdRequest) Reset() {
	*x = IdRequest{}
	mi := &file_internal_transport_grpc_service_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IdRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IdRequest) ProtoMessage() {}

func (x *IdRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_transport_grpc_service_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IdRequest.ProtoReflect.Descriptor instead.
func (*IdRequest) Descriptor() ([]byte, []int) {
	return file_internal_transport_grpc_service_proto_rawDescGZIP(), []int{2}
}

func (x *IdRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type SetEnabledRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            *IdRequest             `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Enabled       bool                   `protobuf:"varint,2,opt,name=enabled,proto3" json:"enabled,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SetEnabledRequest) Reset() {
	*x = SetEnabledRequest{}
	mi := &file_internal_transport_grpc_service_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetEnabledRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetEnabledRequest) ProtoMessage() {}

func (x *SetEnabledRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_transport_grpc_service_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetEnabledRequest.ProtoReflect.Descriptor instead.
func (*SetEnabledRequest) Descriptor() ([]byte, []int) {
	return file_internal_transport_grpc_service_proto_rawDescGZIP(), []int{3}
}

func (x *SetEnabledRequest) GetId() *IdRequest {
	if x != nil {
		return x.Id
	}
	return nil
}

func (x *SetEnabledRequest) GetEnabled() bool {
	if x != nil {
		return x.Enabled
	}
	return false
}

type Empty struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Empty) Reset() {
	*x = Empty{}
	mi := &file_internal_transport_grpc_service_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Empty) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Empty) ProtoMessage() {}

func (x *Empty) ProtoReflect() protoreflect.Message {
	mi := &file_internal_transport_grpc_service_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Empty.ProtoReflect.Descriptor instead.
func (*Empty) Descriptor() ([]byte, []int) {
	return file_internal_transport_grpc_service_proto_rawDescGZIP(), []int{4}
}

var File_internal_transport_grpc_service_proto protoreflect.FileDescriptor

const file_internal_transport_grpc_service_proto_rawDesc = "" +
	"\n" +
	"%internal/transport/grpc/service.proto\x12\x11sub.internal.grpc\x1a\x1cinternal/usecase/model.proto\"\x87\x01\n" +
	"\n" +
	"SetRequest\x12;\n" +
	"\x03raw\x18\x01 \x01(\v2'.sub.internal.usecase.SubscriptionRawPbH\x00R\x03raw\x124\n" +
	"\x03req\x18\x02 \x01(\v2 .sub.internal.usecase.SetRequestH\x00R\x03reqB\x06\n" +
	"\x04data\"M\n" +
	"\x0eGetAllResponse\x12;\n" +
	"\x04subs\x18\x01 \x03(\v2'.sub.internal.usecase.SubscriptionRawPbR\x04subs\"\x1b\n" +
	"\tIdRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"[\n" +
	"\x11SetEnabledRequest\x12,\n" +
	"\x02id\x18\x01 \x01(\v2\x1c.sub.internal.grpc.IdRequestR\x02id\x12\x18\n" +
	"\aenabled\x18\x02 \x01(\bR\aenabled\"\a\n" +
	"\x05Empty2\xf1\x02\n" +
	"\n" +
	"SubService\x12>\n" +
	"\x03Set\x12\x1d.sub.internal.grpc.SetRequest\x1a\x18.sub.internal.grpc.Empty\x12L\n" +
	"\x03Get\x12\x1c.sub.internal.grpc.IdRequest\x1a'.sub.internal.usecase.SubscriptionRawPb\x12E\n" +
	"\x06GetAll\x12\x18.sub.internal.grpc.Empty\x1a!.sub.internal.grpc.GetAllResponse\x12@\n" +
	"\x06Remove\x12\x1c.sub.internal.grpc.IdRequest\x1a\x18.sub.internal.grpc.Empty\x12L\n" +
	"\n" +
	"SetEnabled\x12$.sub.internal.grpc.SetEnabledRequest\x1a\x18.sub.internal.grpc.EmptyB&Z$github.com/brezzgg/sub/internal/grpcb\x06proto3"

var (
	file_internal_transport_grpc_service_proto_rawDescOnce sync.Once
	file_internal_transport_grpc_service_proto_rawDescData []byte
)

func file_internal_transport_grpc_service_proto_rawDescGZIP() []byte {
	file_internal_transport_grpc_service_proto_rawDescOnce.Do(func() {
		file_internal_transport_grpc_service_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_internal_transport_grpc_service_proto_rawDesc), len(file_internal_transport_grpc_service_proto_rawDesc)))
	})
	return file_internal_transport_grpc_service_proto_rawDescData
}

var file_internal_transport_grpc_service_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_internal_transport_grpc_service_proto_goTypes = []any{
	(*SetRequest)(nil),                // 0: sub.internal.grpc.SetRequest
	(*GetAllResponse)(nil),            // 1: sub.internal.grpc.GetAllResponse
	(*IdRequest)(nil),                 // 2: sub.internal.grpc.IdRequest
	(*SetEnabledRequest)(nil),         // 3: sub.internal.grpc.SetEnabledRequest
	(*Empty)(nil),                     // 4: sub.internal.grpc.Empty
	(*usecase.SubscriptionRawPb)(nil), // 5: sub.internal.usecase.SubscriptionRawPb
	(*usecase.SetRequest)(nil),        // 6: sub.internal.usecase.SetRequest
}
var file_internal_transport_grpc_service_proto_depIdxs = []int32{
	5, // 0: sub.internal.grpc.SetRequest.raw:type_name -> sub.internal.usecase.SubscriptionRawPb
	6, // 1: sub.internal.grpc.SetRequest.req:type_name -> sub.internal.usecase.SetRequest
	5, // 2: sub.internal.grpc.GetAllResponse.subs:type_name -> sub.internal.usecase.SubscriptionRawPb
	2, // 3: sub.internal.grpc.SetEnabledRequest.id:type_name -> sub.internal.grpc.IdRequest
	0, // 4: sub.internal.grpc.SubService.Set:input_type -> sub.internal.grpc.SetRequest
	2, // 5: sub.internal.grpc.SubService.Get:input_type -> sub.internal.grpc.IdRequest
	4, // 6: sub.internal.grpc.SubService.GetAll:input_type -> sub.internal.grpc.Empty
	2, // 7: sub.internal.grpc.SubService.Remove:input_type -> sub.internal.grpc.IdRequest
	3, // 8: sub.internal.grpc.SubService.SetEnabled:input_type -> sub.internal.grpc.SetEnabledRequest
	4, // 9: sub.internal.grpc.SubService.Set:output_type -> sub.internal.grpc.Empty
	5, // 10: sub.internal.grpc.SubService.Get:output_type -> sub.internal.usecase.SubscriptionRawPb
	1, // 11: sub.internal.grpc.SubService.GetAll:output_type -> sub.internal.grpc.GetAllResponse
	4, // 12: sub.internal.grpc.SubService.Remove:output_type -> sub.internal.grpc.Empty
	4, // 13: sub.internal.grpc.SubService.SetEnabled:output_type -> sub.internal.grpc.Empty
	9, // [9:14] is the sub-list for method output_type
	4, // [4:9] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_internal_transport_grpc_service_proto_init() }
func file_internal_transport_grpc_service_proto_init() {
	if File_internal_transport_grpc_service_proto != nil {
		return
	}
	file_internal_transport_grpc_service_proto_msgTypes[0].OneofWrappers = []any{
		(*SetRequest_Raw)(nil),
		(*SetRequest_Req)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_internal_transport_grpc_service_proto_rawDesc), len(file_internal_transport_grpc_service_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_internal_transport_grpc_service_proto_goTypes,
		DependencyIndexes: file_internal_transport_grpc_service_proto_depIdxs,
		MessageInfos:      file_internal_transport_grpc_service_proto_msgTypes,
	}.Build()
	File_internal_transport_grpc_service_proto = out.File
	file_internal_transport_grpc_service_proto_goTypes = nil
	file_internal_transport_grpc_service_proto_depIdxs = nil
}
